New MaskSet.get_cmap() implementation
xcube-dev/xcube pull request #1019
Opened 2024-06-19 09:23 UTC by forman

Closes #1011

@konstntokas please also test with original LC data in last webinar notebook.

Checklist:

* [x] Add unit tests and/or doctests in docstrings
* [x] Add docstrings and API docs for any new/modified user-facing classes and functions
* [x] New/modified features documented in `docs/source/*`
* [x] Changes documented in `CHANGES.md`
* [ ] GitHub CI passes
* [ ] AppVeyor CI passes
* [x] Test coverage remains or increases (target 100%)

2024-06-19 11:34 UTC, konstntokas requested changes
We still have the same problem that the user will need to add vmin and vmax manually. I find this, as a user, more confusing then getting vmin and vmax from the `get_cmap` method. See examples below: 

```
land_cover_mask = MaskSet(land_cover_2019.lccs_class)
cmap = land_cover_mask.get_cmap()
land_cover_2019.lccs_class.plot(cmap=cmap)
```
![landcover](https://github.com/xcube-dev/xcube/assets/38956538/548ab755-28a9-40df-83cd-a504b63de5bf)

```
land_cover_mask = MaskSet(land_cover_2019.lccs_class)
cmap = land_cover_mask.get_cmap()
land_cover_2019.lccs_class.plot(cmap=cmap, vmin=0, vmax=220)
plt.show()
```
![landcover_vmin_vax](https://github.com/xcube-dev/xcube/assets/38956538/ac89a899-ec4e-401a-b9c1-37868c8552f1)

The colormap is not really nice, but this method at least buts the values on the correct position. I did something like: 

```
def get_cmap(maskset):
    vals = maskset._flag_values
    extent = vals.max() - vals.min()
    vals_norm = (vals - vals.min()) / extent
    colors = [(0, 0, 0, 0)] + maskset._flag_colors
    color_mapping = [(v, c) for v, c in zip(vals_norm, colors)]
    for v, c in zip(vals, colors):
        print(v, c)
    return matplotlib.colors.LinearSegmentedColormap.from_list(
        str(maskset._flag_var.name), color_mapping, N=len(vals)
    )

land_cover_mask = MaskSet(land_cover_2019.lccs_class)
cmap = get_cmap(land_cover_mask)
land_cover_2019.lccs_class.plot(cmap=cmap, vmin=0, vmax=220)
plt.show()
```
![landcover_oldcmap](https://github.com/xcube-dev/xcube/assets/38956538/6888946e-ff38-4a4e-aab6-4061487cd282)

This gives an aesthetically nicer colormap but distorts the actual values of course. I am indecisive whats better. 

Still we should do something about vmin and vmax, I think. Otherwise a lot of users will run into problems. Would it be possible to add a plotting routine to `MaskSet`?

2024-06-19 11:34 UTC, konstntokas commented on xcube/core/maskset.py
> +) -> Optional[np.ndarray]:
Why Optional?

2024-06-20 12:09 UTC, forman commented
> We still have the same problem that the user will need to add vmin and vmax manually. 

Then, xarray is not calling the color map in the right way. The new color map is a [`matplotlib.colors.ListedColormap`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.ListedColormap.html) and it's documentation (and ensured by our unit tests) says:

_This may be most useful when indexing directly into a colormap_

> I find this, as a user, more confusing then getting vmin and vmax from the `get_cmap` method.

That's right!

2024-06-20 12:24 UTC, forman commented
> The colormap is not really nice, but this method at least buts the values on the correct position.

> This gives an aesthetically nicer colormap but distorts the actual values of course. I am indecisive whats better.

The Land Cover color mapping is not about aesthetics. The ultimate goal is to have an exact match between flag values and assigned color. It is really a pity that the provided `ListedColormap` is not used correctly by xarray. I'll need to update the implementation and also return a `(cmap, norm)` pair then, similar to your code.

2024-06-20 12:25 UTC, forman commented on xcube/core/maskset.py
> +) -> Optional[np.ndarray]:
Forgot to remove.

2024-06-20 12:27 UTC, forman commented
> Still we should do something about vmin and vmax, I think. 

Yes, return a `(cmap, norm)` pair, see above.

> Would it be possible to add a plotting routine to `MaskSet`?

Yes, but let's keep it simple for time being. I will change impl. to return the pair.

2024-06-21 14:00 UTC, konstntokas commented
Including matplotlib.colors.BoundaryNorm the colormap looks like this. The numbers are of course confusing. We would need to create the plot and assign the ticks to the center of each discrete color and assign the tick label to either the flag value or even flag name. 

![landcover_bound_norm](https://github.com/xcube-dev/xcube/assets/38956538/c3198eed-ab36-4724-b969-20f9110b573b)

2024-06-21 14:10 UTC, forman reviewed
See suggestions

2024-06-21 14:10 UTC, forman commented on xcube/core/maskset.py
> +            the corresponding ```matplotlib.colors.BoundaryNorm``` if applicable
```suggestion
            An suitable instance of ``matplotlib.colors.Colormap`` and
            the corresponding ``matplotlib.colors.BoundaryNorm`` if applicable
```

2024-06-21 14:10 UTC, forman commented on xcube/core/maskset.py
> +                levels = np.append(flag_values - 0.5, flag_values[-1] + 0.5)
Why 0.5 shift?

2024-06-24 09:00 UTC, konstntokas commented
The plot now looks like this: 

Code snippet 

```
land_cover_mask = MaskSet(land_cover_2019.lccs_class)
cmap, norm = land_cover_mask.get_cmap()
land_cover_2019.lccs_class.plot.imshow(cmap=cmap, norm=norm)
plt.show()
```

![landcover_bound_norm](https://github.com/xcube-dev/xcube/assets/38956538/8278fb52-f725-4bb1-b74f-db1633191507)

2024-06-24 09:01 UTC, konstntokas commented on xcube/core/maskset.py
> +                levels = np.append(flag_values - 0.5, flag_values[-1] + 0.5)
shift is removed, see plot below.

2024-06-24 09:06 UTC, forman commented
I approve & merge, broken CI has other reasons.

2024-06-24 09:13 UTC, merged