Updates for xarray 2024.3.0 compatibility
xcube-dev/xcube pull request #959
Opened 2024-04-02 16:06 UTC by pont-us

- We now expect float64, not float32, when decoding and scaling variables from a Zarr. See Issue #958.

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] GitHub CI passes
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2024-04-03 13:34 UTC, TonioF approved these changes

2024-04-03 13:35 UTC, forman requested changes
Actually all fine, but either you cover new functionality introduced by `data_vars_only` by tests, or rollback respective changes.

2024-04-03 13:35 UTC, forman commented on xcube/core/chunk.py
> +        dataset = dataset.chunk(chunks=chunk_sizes)
Add unit test to cover new code.

2024-04-03 16:11 UTC, pont-us commented on xcube/core/chunk.py
> +        dataset = dataset.chunk(chunks=chunk_sizes)
Unit tests added.

2024-04-04 09:06 UTC, forman approved these changes
Thanks! 👍

2024-04-04 09:07 UTC, merged