Resolves #963
xcube-dev/xcube pull request #968
Opened 2024-04-11 12:03 UTC by konstntokas

[Description of PR]

Checklist:

* [ ] Add unit tests and/or doctests in docstrings
* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions
* [ ] New/modified features documented in `docs/source/*`
* [ ] Changes documented in `CHANGES.md`
* [ ] GitHub CI passes
* [ ] AppVeyor CI passes
* [ ] Test coverage remains or increases (target 100%)

2024-04-11 15:03 UTC, forman requested changes

2024-04-11 15:03 UTC, forman commented on xcube/util/plugin.py
> +            entry_points.append(_ModuleEntryPoint(module_name))
Could you please explain and/or provide a reference why and when `sys.path` contains `...__path_hook__`.

2024-04-11 15:06 UTC, forman commented
Also, please provide a clear human-readable title for the PR and also always provide a PR description, at least: "Closes #963".

2024-04-12 07:25 UTC, konstntokas commented on xcube/util/plugin.py
> +            entry_points.append(_ModuleEntryPoint(module_name))
I documented it in #963.

2024-04-12 08:40 UTC, forman requested changes
Please look at my suggestion. Note, PR descriptions should not be put in brackets. Just replace the whole text `[Description of PR]` by your description text.

2024-04-12 08:40 UTC, forman commented on xcube/util/plugin.py
> +    # discover plugins if they are installed in a editable mode (see PR #963)
```suggestion
    # Discover plugins if they are installed in a editable mode.
    # See https://github.com/xcube-dev/xcube/issues/963
```

2024-04-12 08:40 UTC, forman commented on xcube/util/plugin.py
> +    # discover plugins if they are installed in a editable mode (see PR #963)
Link to the _issue_, not the PR.

2024-04-12 08:42 UTC, forman commented
Btw, why are the following from the PR checklist not applicable?

- Add unit tests and/or doctests in docstrings
- Add docstrings and API docs for any new/modified user-facing classes and functions
- New/modified features documented in docs/source/*

2024-04-12 08:47 UTC, forman commented
Removed @TejasMorbagal as he is extremely busy.

2024-04-12 09:26 UTC, forman commented on xcube/util/plugin.py
> +            entry_points.append(_ModuleEntryPoint(module_name))
> I documented it in #963.

Thanks!

2024-04-12 09:29 UTC, forman approved these changes

2024-04-12 09:33 UTC, merged